"""initial schema

Generated from app.models metadata. Covers reference data, crew pairings, the workflow
and audit tables, and policy-pack persistence.

Two invariants worth a reviewer's attention:
  * `action.assurance_id` is NOT NULL — no side effect may exist without the immutable
    evaluation that authorised it.
  * `uq_incident_active_per_flight` is a partial unique index implementing FR-6, so a
    60-second weather poll cannot open 60 incidents an hour.

Revision ID: 0001_initial_schema
Revises: None
Create Date: 2026-08-21

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('airport',
        sa.Column('icao_code', sa.String(length=4), nullable=False),
        sa.Column('iata_code', sa.String(length=3), nullable=True),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('city', sa.Text(), nullable=True),
        sa.Column('country', sa.String(length=2), nullable=False),
        sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column('timezone', sa.Text(), nullable=False),
        sa.Column('source_ref', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('icao_code', name=op.f('pk_airport'))
        )
        op.create_table('business_constraint',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('service', sa.String(length=48), nullable=False),
        sa.Column('constraint_key', sa.String(length=48), nullable=False),
        sa.Column('constraint_value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('is_hard', sa.Boolean(), nullable=False),
        sa.Column('version', sa.String(length=32), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_business_constraint')),
        sa.UniqueConstraint('service', 'constraint_key', 'version', name='business_constraint_unique')
        )
        op.create_table('passenger',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reference', sa.String(length=16), nullable=False),
        sa.Column('full_name', sa.Text(), nullable=False),
        sa.Column('email', sa.Text(), nullable=False),
        sa.Column('phone', sa.Text(), nullable=True),
        sa.Column('tier', sa.String(length=12), nullable=False),
        sa.Column('has_special_needs', sa.Boolean(), nullable=False),
        sa.Column('provenance_kind', sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_passenger')),
        sa.UniqueConstraint('reference', name=op.f('uq_passenger_reference'))
        )
        op.create_table('policy_pack',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pack_key', sa.String(length=64), nullable=False),
        sa.Column('version', sa.String(length=32), nullable=False),
        sa.Column('jurisdiction', sa.String(length=8), nullable=False),
        sa.Column('authority', sa.Text(), nullable=False),
        sa.Column('document', sa.Text(), nullable=True),
        sa.Column('effective_from', sa.Date(), nullable=True),
        sa.Column('effective_to', sa.Date(), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),
        sa.Column('verified_mode_eligible', sa.Boolean(), nullable=False),
        sa.Column('ui_label', sa.Text(), nullable=False),
        sa.Column('reviewed_by', sa.Text(), nullable=True),
        sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('pack_hash', sa.String(length=64), nullable=False),
        sa.CheckConstraint("status IN ('draft','official_guidance_dated','approved','retired')", name=op.f('ck_policy_pack_policy_pack_status_valid')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_pack')),
        sa.UniqueConstraint('pack_key', 'version', name='policy_pack_version_unique')
        )
        op.create_table('booking',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pnr', sa.String(length=8), nullable=False),
        sa.Column('passenger_id', sa.Integer(), nullable=False),
        sa.Column('cabin', sa.String(length=12), nullable=False),
        sa.Column('one_way_basic_fare_inr', sa.Integer(), nullable=True),
        sa.Column('airline_fuel_charge_inr', sa.Integer(), nullable=True),
        sa.Column('payment_method', sa.String(length=16), nullable=True),
        sa.Column('contact_info_provided_at_booking', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['passenger_id'], ['passenger.id'], name=op.f('fk_booking_passenger_id_passenger')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_booking')),
        sa.UniqueConstraint('pnr', name=op.f('uq_booking_pnr'))
        )
        op.create_table('crew_member',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reference', sa.String(length=16), nullable=False),
        sa.Column('full_name', sa.Text(), nullable=False),
        sa.Column('role', sa.String(length=16), nullable=False),
        sa.Column('base_icao', sa.String(length=4), nullable=False),
        sa.Column('duty_hours_limit', sa.SmallInteger(), nullable=True),
        sa.Column('provenance_kind', sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(['base_icao'], ['airport.icao_code'], name=op.f('fk_crew_member_base_icao_airport')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_crew_member')),
        sa.UniqueConstraint('reference', name=op.f('uq_crew_member_reference'))
        )
        op.create_table('flight',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('flight_number', sa.String(length=10), nullable=False),
        sa.Column('airline_code', sa.String(length=3), nullable=False),
        sa.Column('origin_icao', sa.String(length=4), nullable=False),
        sa.Column('destination_icao', sa.String(length=4), nullable=False),
        sa.Column('scheduled_departure', sa.DateTime(timezone=True), nullable=False),
        sa.Column('scheduled_arrival', sa.DateTime(timezone=True), nullable=False),
        sa.Column('estimated_departure', sa.DateTime(timezone=True), nullable=True),
        sa.Column('block_time_minutes', sa.SmallInteger(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('is_domestic', sa.Boolean(), nullable=False),
        sa.Column('gate', sa.String(length=8), nullable=True),
        sa.Column('provenance_kind', sa.String(length=16), nullable=False),
        sa.Column('source_ref', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('block_time_minutes > 0', name=op.f('ck_flight_flight_block_time_positive')),
        sa.ForeignKeyConstraint(['destination_icao'], ['airport.icao_code'], name=op.f('fk_flight_destination_icao_airport')),
        sa.ForeignKeyConstraint(['origin_icao'], ['airport.icao_code'], name=op.f('fk_flight_origin_icao_airport')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_flight'))
        )
        op.create_index('ix_flight_origin_scheduled', 'flight', ['origin_icao', 'scheduled_departure'], unique=False)
        op.create_index('ix_flight_status', 'flight', ['status'], unique=False)
        op.create_table('hotel',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('airport_icao', sa.String(length=4), nullable=False),
        sa.Column('rate_inr', sa.Integer(), nullable=False),
        sa.Column('is_partner', sa.Boolean(), nullable=False),
        sa.Column('distance_km', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('total_rooms', sa.SmallInteger(), nullable=False),
        sa.Column('available_rooms', sa.SmallInteger(), nullable=False),
        sa.Column('provenance_kind', sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(['airport_icao'], ['airport.icao_code'], name=op.f('fk_hotel_airport_icao_airport')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel'))
        )
        op.create_index(op.f('ix_hotel_airport_icao'), 'hotel', ['airport_icao'], unique=False)
        op.create_table('incident_group',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reference', sa.String(length=32), nullable=False),
        sa.Column('root_cause', sa.String(length=20), nullable=False),
        sa.Column('airport_icao', sa.String(length=4), nullable=False),
        sa.Column('severity', sa.String(length=12), nullable=False),
        sa.Column('state', sa.String(length=20), nullable=False),
        sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('demo_dataset_id', sa.String(length=32), nullable=True),
        sa.CheckConstraint("state IN ('detected','assessing','planning','assuring','awaiting_approval','executing','resolved','blocked','failed')", name=op.f('ck_incident_group_incident_group_state_valid')),
        sa.ForeignKeyConstraint(['airport_icao'], ['airport.icao_code'], name=op.f('fk_incident_group_airport_icao_airport')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_group')),
        sa.UniqueConstraint('reference', name=op.f('uq_incident_group_reference'))
        )
        op.create_index(op.f('ix_incident_group_demo_dataset_id'), 'incident_group', ['demo_dataset_id'], unique=False)
        op.create_table('pairing',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reference', sa.String(length=16), nullable=False),
        sa.Column('base_icao', sa.String(length=4), nullable=False),
        sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['base_icao'], ['airport.icao_code'], name=op.f('fk_pairing_base_icao_airport')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pairing')),
        sa.UniqueConstraint('reference', name=op.f('uq_pairing_reference'))
        )
        op.create_table('policy_rule',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('policy_pack_id', sa.Integer(), nullable=False),
        sa.Column('rule_key', sa.String(length=96), nullable=False),
        sa.Column('event_type', sa.String(length=32), nullable=False),
        sa.Column('condition_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('entitlement_json', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('source_clause_refs', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('review_status', sa.String(length=32), nullable=False),
        sa.Column('excluded_from_evaluation', sa.Boolean(), nullable=False),
        sa.Column('interpretation', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['policy_pack_id'], ['policy_pack.id'], name=op.f('fk_policy_rule_policy_pack_id_policy_pack')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_rule')),
        sa.UniqueConstraint('policy_pack_id', 'rule_key', name='policy_rule_unique')
        )
        op.create_table('policy_source_document',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('policy_pack_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('source_url', sa.Text(), nullable=False),
        sa.Column('published_revision', sa.Text(), nullable=True),
        sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('content_hash', sa.String(length=64), nullable=False),
        sa.Column('licence_note', sa.Text(), nullable=True),
        sa.Column('local_path', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['policy_pack_id'], ['policy_pack.id'], name=op.f('fk_policy_source_document_policy_pack_id_policy_pack')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_source_document'))
        )
        op.create_table('runway',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('airport_icao', sa.String(length=4), nullable=False),
        sa.Column('designator', sa.String(length=8), nullable=False),
        sa.Column('heading_degrees_true', sa.SmallInteger(), nullable=False),
        sa.Column('length_ft', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.CheckConstraint('heading_degrees_true >= 0 AND heading_degrees_true <= 360', name=op.f('ck_runway_runway_heading_range')),
        sa.ForeignKeyConstraint(['airport_icao'], ['airport.icao_code'], name=op.f('fk_runway_airport_icao_airport')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_runway'))
        )
        op.create_index(op.f('ix_runway_airport_icao'), 'runway', ['airport_icao'], unique=False)
        op.create_table('transport_vendor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('airport_icao', sa.String(length=4), nullable=False),
        sa.Column('vehicle_type', sa.String(length=16), nullable=False),
        sa.Column('seats_per_vehicle', sa.SmallInteger(), nullable=False),
        sa.Column('available_vehicles', sa.SmallInteger(), nullable=False),
        sa.Column('cost_per_vehicle_inr', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['airport_icao'], ['airport.icao_code'], name=op.f('fk_transport_vendor_airport_icao_airport')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_transport_vendor'))
        )
        op.create_table('weather_observation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('airport_icao', sa.String(length=4), nullable=False),
        sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('wind_speed_kt', sa.SmallInteger(), nullable=True),
        sa.Column('wind_direction_deg', sa.SmallInteger(), nullable=True),
        sa.Column('visibility_m', sa.Integer(), nullable=True),
        sa.Column('ceiling_ft', sa.Integer(), nullable=True),
        sa.Column('precipitation', sa.Text(), nullable=True),
        sa.Column('raw_metar', sa.Text(), nullable=True),
        sa.Column('provenance_kind', sa.String(length=16), nullable=False),
        sa.Column('provenance_provider', sa.Text(), nullable=False),
        sa.Column('source_ref', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['airport_icao'], ['airport.icao_code'], name=op.f('fk_weather_observation_airport_icao_airport')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_observation'))
        )
        op.create_index('ix_weather_observation_airport_observed', 'weather_observation', ['airport_icao', 'observed_at'], unique=False)
        op.create_table('booking_segment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=False),
        sa.Column('flight_id', sa.Integer(), nullable=False),
        sa.Column('segment_order', sa.SmallInteger(), nullable=False),
        sa.Column('checked_in_on_time', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('fk_booking_segment_booking_id_booking')),
        sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], name=op.f('fk_booking_segment_flight_id_flight')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_segment'))
        )
        op.create_index(op.f('ix_booking_segment_flight_id'), 'booking_segment', ['flight_id'], unique=False)
        op.create_table('crew_pairing_assignment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('crew_member_id', sa.Integer(), nullable=False),
        sa.Column('pairing_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['crew_member_id'], ['crew_member.id'], name=op.f('fk_crew_pairing_assignment_crew_member_id_crew_member')),
        sa.ForeignKeyConstraint(['pairing_id'], ['pairing.id'], name=op.f('fk_crew_pairing_assignment_pairing_id_pairing')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_crew_pairing_assignment')),
        sa.UniqueConstraint('crew_member_id', 'pairing_id', name='crew_pairing_unique')
        )
        op.create_table('pairing_leg',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('pairing_id', sa.Integer(), nullable=False),
        sa.Column('flight_id', sa.Integer(), nullable=False),
        sa.Column('leg_order', sa.SmallInteger(), nullable=False),
        sa.Column('role', sa.String(length=16), nullable=False),
        sa.Column('min_connection_minutes', sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], name=op.f('fk_pairing_leg_flight_id_flight')),
        sa.ForeignKeyConstraint(['pairing_id'], ['pairing.id'], name=op.f('fk_pairing_leg_pairing_id_pairing')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pairing_leg')),
        sa.UniqueConstraint('pairing_id', 'leg_order', name='pairing_leg_order_unique')
        )
        op.create_index(op.f('ix_pairing_leg_flight_id'), 'pairing_leg', ['flight_id'], unique=False)
        op.create_index('ix_pairing_leg_flight_pairing', 'pairing_leg', ['flight_id', 'pairing_id'], unique=False)
        op.create_index(op.f('ix_pairing_leg_pairing_id'), 'pairing_leg', ['pairing_id'], unique=False)
        op.create_table('policy_clause',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_document_id', sa.Integer(), nullable=False),
        sa.Column('clause_ref', sa.String(length=64), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('extraction_method', sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(['source_document_id'], ['policy_source_document.id'], name=op.f('fk_policy_clause_source_document_id_policy_source_document')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_clause')),
        sa.UniqueConstraint('source_document_id', 'clause_ref', name='policy_clause_unique')
        )
        op.create_table('prediction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('flight_id', sa.Integer(), nullable=False),
        sa.Column('airport_icao', sa.String(length=4), nullable=False),
        sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('risk_index', sa.SmallInteger(), nullable=False),
        sa.Column('risk_level', sa.String(length=12), nullable=False),
        sa.Column('rule_version', sa.String(length=32), nullable=False),
        sa.Column('factors', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.CheckConstraint('risk_index >= 0 AND risk_index <= 100', name=op.f('ck_prediction_prediction_index_range')),
        sa.ForeignKeyConstraint(['airport_icao'], ['airport.icao_code'], name=op.f('fk_prediction_airport_icao_airport')),
        sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], name=op.f('fk_prediction_flight_id_flight')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction'))
        )
        op.create_table('incident',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reference', sa.String(length=32), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.Column('flight_id', sa.Integer(), nullable=False),
        sa.Column('prediction_id', sa.Integer(), nullable=True),
        sa.Column('trigger_type', sa.String(length=20), nullable=False),
        sa.Column('severity', sa.String(length=12), nullable=False),
        sa.Column('state', sa.String(length=20), nullable=False),
        sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('demo_dataset_id', sa.String(length=32), nullable=True),
        sa.CheckConstraint("state IN ('detected','assessing','planning','assuring','awaiting_approval','executing','resolved','blocked','failed')", name=op.f('ck_incident_incident_state_valid')),
        sa.ForeignKeyConstraint(['flight_id'], ['flight.id'], name=op.f('fk_incident_flight_id_flight')),
        sa.ForeignKeyConstraint(['group_id'], ['incident_group.id'], name=op.f('fk_incident_group_id_incident_group')),
        sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], name=op.f('fk_incident_prediction_id_prediction')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_incident')),
        sa.UniqueConstraint('reference', name=op.f('uq_incident_reference'))
        )
        op.create_index(op.f('ix_incident_demo_dataset_id'), 'incident', ['demo_dataset_id'], unique=False)
        op.create_index(op.f('ix_incident_group_id'), 'incident', ['group_id'], unique=False)
        op.create_index('uq_incident_active_per_flight', 'incident', ['flight_id'], unique=True, postgresql_where=sa.text("state NOT IN ('resolved','blocked','failed')"), sqlite_where=sa.text("state NOT IN ('resolved','blocked','failed')"))
        op.create_table('pairing_impact',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('incident_group_id', sa.Integer(), nullable=False),
        sa.Column('pairing_id', sa.Integer(), nullable=False),
        sa.Column('source_flight_id', sa.Integer(), nullable=False),
        sa.Column('affected_leg_id', sa.Integer(), nullable=False),
        sa.Column('mechanism', sa.String(length=24), nullable=False),
        sa.Column('detail', sa.Text(), nullable=True),
        sa.Column('is_at_risk', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['affected_leg_id'], ['pairing_leg.id'], name=op.f('fk_pairing_impact_affected_leg_id_pairing_leg')),
        sa.ForeignKeyConstraint(['incident_group_id'], ['incident_group.id'], name=op.f('fk_pairing_impact_incident_group_id_incident_group')),
        sa.ForeignKeyConstraint(['pairing_id'], ['pairing.id'], name=op.f('fk_pairing_impact_pairing_id_pairing')),
        sa.ForeignKeyConstraint(['source_flight_id'], ['flight.id'], name=op.f('fk_pairing_impact_source_flight_id_flight')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_pairing_impact')),
        sa.UniqueConstraint('incident_group_id', 'pairing_id', 'affected_leg_id', name='pairing_impact_unique')
        )
        op.create_index(op.f('ix_pairing_impact_incident_group_id'), 'pairing_impact', ['incident_group_id'], unique=False)
        op.create_table('decision_log',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('incident_id', sa.Integer(), nullable=True),
        sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('stage', sa.String(length=20), nullable=False),
        sa.Column('actor', sa.String(length=48), nullable=False),
        sa.Column('event_type', sa.String(length=48), nullable=False),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
        sa.Column('correlation_id', sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_decision_log_incident_id_incident')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_log'))
        )
        op.create_index(op.f('ix_decision_log_incident_id'), 'decision_log', ['incident_id'], unique=False)
        op.create_index('ix_decision_log_incident_occurred', 'decision_log', ['incident_id', 'occurred_at'], unique=False)
        op.create_table('incident_outcome',
        sa.Column('incident_id', sa.Integer(), nullable=False),
        sa.Column('resolved', sa.Boolean(), nullable=False),
        sa.Column('passengers_affected', sa.Integer(), nullable=True),
        sa.Column('passengers_reaccommodated', sa.Integer(), nullable=True),
        sa.Column('connections_protected', sa.Integer(), nullable=True),
        sa.Column('total_cost_inr', sa.Integer(), nullable=True),
        sa.Column('resolution_minutes', sa.Integer(), nullable=True),
        sa.Column('operator_rating', sa.SmallInteger(), nullable=True),
        sa.Column('operator_notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_incident_outcome_incident_id_incident')),
        sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_incident_outcome'))
        )
        op.create_table('plan',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('incident_id', sa.Integer(), nullable=False),
        sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('generator', sa.Text(), nullable=False),
        sa.Column('prompt_version', sa.String(length=32), nullable=True),
        sa.Column('model_self_report', sa.SmallInteger(), nullable=True),
        sa.Column('rationale', sa.Text(), nullable=True),
        sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
        sa.Column('retrieved_incident_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_plan_incident_id_incident')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_plan'))
        )
        op.create_index(op.f('ix_plan_incident_id'), 'plan', ['incident_id'], unique=False)
        op.create_table('policy_applicability',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('incident_id', sa.Integer(), nullable=False),
        sa.Column('policy_pack_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('basis', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('required_facts', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('missing_facts', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('conflict_disposition', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('resolver_version', sa.String(length=32), nullable=False),
        sa.Column('resolver_hash', sa.String(length=64), nullable=False),
        sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("status IN ('applicable','not_applicable','undetermined')", name=op.f('ck_policy_applicability_policy_applicability_status_valid')),
        sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_policy_applicability_incident_id_incident')),
        sa.ForeignKeyConstraint(['policy_pack_id'], ['policy_pack.id'], name=op.f('fk_policy_applicability_policy_pack_id_policy_pack')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_applicability'))
        )
        op.create_index(op.f('ix_policy_applicability_incident_id'), 'policy_applicability', ['incident_id'], unique=False)
        op.create_table('entitlement_evaluation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('incident_id', sa.Integer(), nullable=False),
        sa.Column('applicability_id', sa.Integer(), nullable=False),
        sa.Column('policy_pack_id', sa.Integer(), nullable=False),
        sa.Column('policy_rule_id', sa.Integer(), nullable=False),
        sa.Column('input_facts', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('result', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['applicability_id'], ['policy_applicability.id'], name=op.f('fk_entitlement_evaluation_applicability_id_policy_applicability')),
        sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], name=op.f('fk_entitlement_evaluation_incident_id_incident')),
        sa.ForeignKeyConstraint(['policy_pack_id'], ['policy_pack.id'], name=op.f('fk_entitlement_evaluation_policy_pack_id_policy_pack')),
        sa.ForeignKeyConstraint(['policy_rule_id'], ['policy_rule.id'], name=op.f('fk_entitlement_evaluation_policy_rule_id_policy_rule')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlement_evaluation'))
        )
        op.create_index(op.f('ix_entitlement_evaluation_incident_id'), 'entitlement_evaluation', ['incident_id'], unique=False)
        op.create_table('plan_task',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=False),
        sa.Column('action_type', sa.String(length=32), nullable=False),
        sa.Column('task_order', sa.SmallInteger(), nullable=False),
        sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('target_refs', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('state', sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], name=op.f('fk_plan_task_plan_id_plan')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_task'))
        )
        op.create_index(op.f('ix_plan_task_plan_id'), 'plan_task', ['plan_id'], unique=False)
        op.create_table('assurance_evaluation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_task_id', sa.Integer(), nullable=False),
        sa.Column('decision', sa.String(length=20), nullable=False),
        sa.Column('risk_tier', sa.String(length=8), nullable=False),
        sa.Column('check_results', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('blocking_reasons', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
        sa.Column('config_version', sa.String(length=32), nullable=False),
        sa.Column('config_hash', sa.String(length=64), nullable=False),
        sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['plan_task_id'], ['plan_task.id'], name=op.f('fk_assurance_evaluation_plan_task_id_plan_task')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_assurance_evaluation'))
        )
        op.create_index(op.f('ix_assurance_evaluation_plan_task_id'), 'assurance_evaluation', ['plan_task_id'], unique=False)
        op.create_table('human_decision',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('assurance_id', sa.Integer(), nullable=False),
        sa.Column('decision', sa.String(length=12), nullable=False),
        sa.Column('actor_id', sa.String(length=64), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("decision IN ('approved','rejected')", name=op.f('ck_human_decision_human_decision_valid')),
        sa.ForeignKeyConstraint(['assurance_id'], ['assurance_evaluation.id'], name=op.f('fk_human_decision_assurance_id_assurance_evaluation')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_human_decision')),
        sa.UniqueConstraint('assurance_id', name=op.f('uq_human_decision_assurance_id'))
        )
        op.create_table('action',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_task_id', sa.Integer(), nullable=False),
        sa.Column('assurance_id', sa.Integer(), nullable=False),
        sa.Column('human_decision_id', sa.Integer(), nullable=True),
        sa.Column('actor', sa.String(length=48), nullable=False),
        sa.Column('idempotency_key', sa.String(length=128), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('cost_inr', sa.Integer(), nullable=True),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
        sa.Column('provenance_kind', sa.String(length=16), nullable=False),
        sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['assurance_id'], ['assurance_evaluation.id'], name=op.f('fk_action_assurance_id_assurance_evaluation')),
        sa.ForeignKeyConstraint(['human_decision_id'], ['human_decision.id'], name=op.f('fk_action_human_decision_id_human_decision')),
        sa.ForeignKeyConstraint(['plan_task_id'], ['plan_task.id'], name=op.f('fk_action_plan_task_id_plan_task')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_action')),
        sa.UniqueConstraint('idempotency_key', name=op.f('uq_action_idempotency_key'))
        )
        op.create_index(op.f('ix_action_plan_task_id'), 'action', ['plan_task_id'], unique=False)
        op.create_table('hotel_reservation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('action_id', sa.Integer(), nullable=True),
        sa.Column('hotel_id', sa.Integer(), nullable=False),
        sa.Column('booking_id', sa.Integer(), nullable=True),
        sa.Column('rooms', sa.SmallInteger(), nullable=False),
        sa.Column('nights', sa.SmallInteger(), nullable=False),
        sa.Column('rate_inr', sa.Integer(), nullable=False),
        sa.Column('is_simulated', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['action_id'], ['action.id'], name=op.f('fk_hotel_reservation_action_id_action')),
        sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name=op.f('fk_hotel_reservation_booking_id_booking')),
        sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], name=op.f('fk_hotel_reservation_hotel_id_hotel')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_hotel_reservation')),
        sa.UniqueConstraint('action_id', 'hotel_id', 'booking_id', name='hotel_reservation_unique')
        )
        op.create_table('notification',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('action_id', sa.Integer(), nullable=True),
        sa.Column('passenger_id', sa.Integer(), nullable=False),
        sa.Column('channel', sa.String(length=8), nullable=False),
        sa.Column('delivery_mode', sa.String(length=12), nullable=False),
        sa.Column('subject', sa.Text(), nullable=True),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('provider_message_id', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=12), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['action_id'], ['action.id'], name=op.f('fk_notification_action_id_action')),
        sa.ForeignKeyConstraint(['passenger_id'], ['passenger.id'], name=op.f('fk_notification_passenger_id_passenger')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
        )
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('notification')
        op.drop_table('hotel_reservation')
        op.drop_index(op.f('ix_action_plan_task_id'), table_name='action')
        op.drop_table('action')
        op.drop_table('human_decision')
        op.drop_index(op.f('ix_assurance_evaluation_plan_task_id'), table_name='assurance_evaluation')
        op.drop_table('assurance_evaluation')
        op.drop_index(op.f('ix_plan_task_plan_id'), table_name='plan_task')
        op.drop_table('plan_task')
        op.drop_index(op.f('ix_entitlement_evaluation_incident_id'), table_name='entitlement_evaluation')
        op.drop_table('entitlement_evaluation')
        op.drop_index(op.f('ix_policy_applicability_incident_id'), table_name='policy_applicability')
        op.drop_table('policy_applicability')
        op.drop_index(op.f('ix_plan_incident_id'), table_name='plan')
        op.drop_table('plan')
        op.drop_table('incident_outcome')
        op.drop_index(op.f('ix_decision_log_incident_id'), table_name='decision_log')
        op.drop_index('ix_decision_log_incident_occurred', table_name='decision_log')
        op.drop_table('decision_log')
        op.drop_index(op.f('ix_pairing_impact_incident_group_id'), table_name='pairing_impact')
        op.drop_table('pairing_impact')
        op.drop_index(op.f('ix_incident_demo_dataset_id'), table_name='incident')
        op.drop_index(op.f('ix_incident_group_id'), table_name='incident')
        op.drop_index('uq_incident_active_per_flight', table_name='incident', postgresql_where=sa.text("state NOT IN ('resolved','blocked','failed')"), sqlite_where=sa.text("state NOT IN ('resolved','blocked','failed')"))
        op.drop_table('incident')
        op.drop_table('prediction')
        op.drop_table('policy_clause')
        op.drop_index(op.f('ix_pairing_leg_flight_id'), table_name='pairing_leg')
        op.drop_index('ix_pairing_leg_flight_pairing', table_name='pairing_leg')
        op.drop_index(op.f('ix_pairing_leg_pairing_id'), table_name='pairing_leg')
        op.drop_table('pairing_leg')
        op.drop_table('crew_pairing_assignment')
        op.drop_index(op.f('ix_booking_segment_flight_id'), table_name='booking_segment')
        op.drop_table('booking_segment')
        op.drop_index('ix_weather_observation_airport_observed', table_name='weather_observation')
        op.drop_table('weather_observation')
        op.drop_table('transport_vendor')
        op.drop_index(op.f('ix_runway_airport_icao'), table_name='runway')
        op.drop_table('runway')
        op.drop_table('policy_source_document')
        op.drop_table('policy_rule')
        op.drop_table('pairing')
        op.drop_index(op.f('ix_incident_group_demo_dataset_id'), table_name='incident_group')
        op.drop_table('incident_group')
        op.drop_index(op.f('ix_hotel_airport_icao'), table_name='hotel')
        op.drop_table('hotel')
        op.drop_index('ix_flight_origin_scheduled', table_name='flight')
        op.drop_index('ix_flight_status', table_name='flight')
        op.drop_table('flight')
        op.drop_table('crew_member')
        op.drop_table('booking')
        op.drop_table('policy_pack')
        op.drop_table('passenger')
        op.drop_table('business_constraint')
        op.drop_table('airport')
        # ### end Alembic commands ###
