/**
 * Executive Report — `/reports/:incidentId`. Phase 3 reasoning agent.
 *
 * Reads `GET /reports/{id}`, which is now backed by the Report Generator agent rather than a fixture.
 * The report is a read-only artifact: it never enters assurance, triggers no action, and modifies no
 * row. It is the model's contribution to the executive display, not to the recovery.
 *
 * When `LLM_MODE=off` the endpoint returns 404 with a message naming the mode. This screen renders
 * that as a stated limitation, not an error.
 *
 * Owner: Stream D.
 */

import { useParams } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';

import { api, ApiError } from '@/api/client';
import { EmptyState, ErrorState, LoadingState, MonoValue, Panel } from '@/components/ui/primitives';

export function ReportScreen() {
  const { incidentId = '' } = useParams();

  const reportQuery = useQuery({
    queryKey: ['report', incidentId],
    queryFn: () => api.report(incidentId),
    enabled: incidentId.length > 0,
  });

  if (reportQuery.isLoading) {
    return (
      <Panel title="Executive report">
        <div className="h-[440px]">
          <LoadingState label="Generating report" />
        </div>
      </Panel>
    );
  }

  if (reportQuery.error) {
    const error = reportQuery.error instanceof ApiError ? reportQuery.error : null;
    // 404 with llm_mode=off is not an error — it is a stated configuration fact.
    const isOff = error?.status === 404 && error.details?.llm_mode === 'off';
    if (isOff) {
      return (
        <Panel title="Executive report">
          <EmptyState
            title="Report generation is not available"
            description="LLM_MODE is set to off. The system operates without any model — the deterministic playbook is the recovery path. Set LLM_MODE=fixture or LLM_MODE=live to enable reasoning agents."
          />
        </Panel>
      );
    }
    return (
      <ErrorState
        code={error?.code ?? 'INTERNAL_ERROR'}
        message={error?.message ?? `Could not generate report for ${incidentId}.`}
        correlationId={error?.correlationId ?? null}
        onRetry={() => void reportQuery.refetch()}
      />
    );
  }

  const report = reportQuery.data;
  if (!report) return null;

  return (
    <div className="flex min-h-0 flex-col gap-3">
      <Panel
        title="Executive report"
        actions={
          <span className="flex items-center gap-3 text-caption text-fg-muted">
            <span>
              generated by <MonoValue muted>{report.generator}</MonoValue>
            </span>
            {report.prompt_version && (
              <span>
                prompt <MonoValue muted>{report.prompt_version}</MonoValue>
              </span>
            )}
            <span>
              mode <MonoValue muted>{report.llm_mode}</MonoValue>
            </span>
          </span>
        }
      >
        {/* The summary is the one-paragraph answer a C-suite reader needs. */}
        <div className="border-b border-border-subtle px-3 py-3">
          <p className="max-w-[86ch] text-body text-fg">{report.summary}</p>
        </div>

        {/* Structured sections from the model. */}
        {report.sections.map((section, index) => (
          <div key={index} className="border-b border-border-subtle px-3 py-2.5">
            <h3 className="text-label uppercase text-fg-muted">{section.heading}</h3>
            <p className="mt-1 max-w-[86ch] text-body text-fg-secondary">{section.body}</p>
          </div>
        ))}

        {/* Metric references — what the model read off to compose the report. */}
        {report.metric_refs.length > 0 && (
          <div className="border-b border-border-subtle px-3 py-2">
            <span className="text-label uppercase text-fg-muted">Sources cited</span>
            <div className="mt-1 flex flex-wrap gap-1.5">
              {report.metric_refs.map((ref) => (
                <MonoValue key={ref} muted className="text-caption">
                  {ref}
                </MonoValue>
              ))}
            </div>
          </div>
        )}

        {/* Audit: tokens, latency, model. Not for control flow — for the audit trail. */}
        <div className="flex flex-wrap items-center gap-4 px-3 py-2 text-caption text-fg-muted">
          {report.audit.latency_ms !== null && (
            <span>
              latency <MonoValue muted>{report.audit.latency_ms}ms</MonoValue>
            </span>
          )}
          {report.audit.input_tokens !== null && (
            <span>
              tokens{' '}
              <MonoValue muted>
                {report.audit.input_tokens}+{report.audit.output_tokens}
              </MonoValue>
            </span>
          )}
          <span>
            This report is a model-generated artifact. It does not enter assurance, trigger any
            action, or modify any record.
          </span>
        </div>
      </Panel>

      <ExplanationPanel incidentId={incidentId} />
    </div>
  );
}

/**
 * The Explainer agent's account of the same recovery.
 *
 * On this route alongside the report because they are one subject read two ways: the report
 * summarises the figures, the explanation justifies the ordering. Absent is a normal outcome and
 * renders as a stated absence, never as an error — the recorded actions are complete without it.
 */
function ExplanationPanel({ incidentId }: { incidentId: string }) {
  const query = useQuery({
    queryKey: ['explanation', incidentId],
    queryFn: () => api.explanation(incidentId),
    enabled: incidentId.length > 0,
    retry: false,
  });

  if (query.isLoading) {
    return (
      <Panel title="Why this recovery">
        <div className="h-[140px]">
          <LoadingState label="Loading explanation" />
        </div>
      </Panel>
    );
  }

  if (query.error || !query.data) {
    const error = query.error instanceof ApiError ? query.error : null;
    const mode = typeof error?.details?.llm_mode === 'string' ? error.details.llm_mode : null;
    const reason = typeof error?.details?.reason === 'string' ? error.details.reason : null;
    return (
      <Panel title="Why this recovery">
        <EmptyState
          title={mode === 'off' ? 'No explanation was generated' : 'No explanation is available'}
          description={
            reason ??
            error?.message ??
            'The Explainer agent produced no output. The recorded actions are unaffected.'
          }
        />
      </Panel>
    );
  }

  const explanation = query.data;
  return (
    <Panel
      title="Why this recovery"
      actions={
        <span className="flex items-center gap-3 text-caption text-fg-muted">
          <span>
            by <MonoValue muted>{explanation.generator}</MonoValue>
          </span>
          <span>
            source <MonoValue muted>{explanation.source}</MonoValue>
          </span>
        </span>
      }
    >
      <div className="px-3 py-2.5">
        {/* The model writes paragraphs separated by a blank line. Rendered as paragraphs rather
            than one block, because a wall of text is not read. */}
        {explanation.explanation.split('\n\n').map((paragraph, index) => (
          <p key={index} className="mb-2 max-w-[86ch] text-body text-fg-secondary last:mb-0">
            {paragraph}
          </p>
        ))}
      </div>

      {explanation.citation_refs.length > 0 && (
        <div className="border-t border-border-subtle px-3 py-2">
          <span className="text-label uppercase text-fg-muted">Cited</span>
          <div className="mt-1 flex flex-wrap gap-1.5">
            {explanation.citation_refs.map((ref) => (
              <MonoValue key={ref} muted className="text-caption">
                {ref}
              </MonoValue>
            ))}
          </div>
        </div>
      )}

      <p className="border-t border-border-subtle px-3 py-2 text-caption text-fg-muted">
        An explanation of a recovery that already happened. It authorises nothing and changed
        nothing.
      </p>
    </Panel>
  );
}
